package com.cyclonercm.ai.models;



import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * Generated Test Code Model
 * Represents a test generated by TestGenerationAgent
 *
 * @author Nolo (Senior QA AI Agent)
 * @version 1.0
 * @date January 06, 2026
 */
public class GeneratedTestCode {

    private String code;
    private String className;
    private String filePath;
    private LocalDateTime generatedAt;
    private boolean saved;
    private String message;

    /**
     * Constructor
     */
    public GeneratedTestCode(String code, String className, String filePath,
                             LocalDateTime generatedAt, boolean saved, String message) {
        this.code = code;
        this.className = className;
        this.filePath = filePath;
        this.generatedAt = generatedAt;
        this.saved = saved;
        this.message = message;
    }

    // Getters
    public String getCode() { return code; }
    public String getClassName() { return className; }
    public String getFilePath() { return filePath; }
    public LocalDateTime getGeneratedAt() { return generatedAt; }
    public boolean isSaved() { return saved; }
    public String getMessage() { return message; }

    // Setters
    public void setCode(String code) { this.code = code; }
    public void setClassName(String className) { this.className = className; }
    public void setFilePath(String filePath) { this.filePath = filePath; }
    public void setSaved(boolean saved) { this.saved = saved; }
    public void setMessage(String message) { this.message = message; }

    /**
     * Get code line count
     */
    public int getLineCount() {
        if (code == null) return 0;
        return code.split("\n").length;
    }

    /**
     * Get timestamp as formatted string
     */
    public String getFormattedTimestamp() {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        return generatedAt.format(formatter);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("╔════════════════════════════════════════════════════════════════╗\n");
        sb.append("║           GENERATED TEST CODE                                  ║\n");
        sb.append("╚════════════════════════════════════════════════════════════════╝\n\n");
        sb.append("Class Name: ").append(className).append("\n");
        sb.append("File Path: ").append(filePath).append("\n");
        sb.append("Generated: ").append(getFormattedTimestamp()).append("\n");
        sb.append("Lines of Code: ").append(getLineCount()).append("\n");
        sb.append("Saved: ").append(saved ? "✅ YES" : "❌ NO").append("\n");
        sb.append("Message: ").append(message).append("\n");

        return sb.toString();
    }
}